name: flutter_l10n
description: A dart library that generates Flutter localization code from ARB file.
version: 1.0.0
homepage: https://github.com/chenenyu/flutter_l10n

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  dart_style: ^2.2.3
  file: ">=6.1.2 <8.0.0"
  intl: ^0.18.0
  path: ^1.8.0
  yaml: ^3.0.0
